# Generated by Django 6.1 on 2026-09-01 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان مدرک')),
                ('issuer', models.CharField(blank=True, max_length=200, verbose_name='صادرکننده')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('image', models.ImageField(blank=True, null=True, upload_to='certificates/images/', verbose_name='تصویر مدرک')),
                ('file', models.FileField(blank=True, null=True, upload_to='certificates/files/', verbose_name='فایل مدرک')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='تاریخ صدور')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'مجوز یا مدرک',
                'verbose_name_plural': 'مجوزها و مدارک',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام تجهیز')),
                ('model', models.CharField(blank=True, max_length=150, verbose_name='مدل')),
                ('manufacturer', models.CharField(blank=True, max_length=150, verbose_name='سازنده')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('image', models.ImageField(blank=True, null=True, upload_to='equipment/', verbose_name='تصویر')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'تجهیز',
                'verbose_name_plural': 'تجهیزات',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('short_name', models.CharField(blank=True, max_length=50, verbose_name='نام اختصاری')),
                ('category', models.CharField(choices=[('ndt', 'آزمون\u200cهای غیرمخرب NDT'), ('dt', 'آزمون\u200cهای مخرب DT'), ('inspection', 'بازرسی فنی')], max_length=20, verbose_name='دسته\u200cبندی')),
                ('short_description', models.CharField(blank=True, max_length=300, verbose_name='توضیح کوتاه')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='تصویر')),
                ('is_featured', models.BooleanField(default=False, verbose_name='نمایش در صفحه اصلی')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'خدمت',
                'verbose_name_plural': 'خدمات',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان پروژه')),
                ('client', models.CharField(blank=True, max_length=200, verbose_name='کارفرما')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='محل پروژه')),
                ('description', models.TextField(blank=True, verbose_name='شرح پروژه')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='تصویر اصلی')),
                ('project_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پروژه')),
                ('is_featured', models.BooleanField(default=False, verbose_name='پروژه شاخص')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('services', models.ManyToManyField(blank=True, related_name='projects', to='website.service', verbose_name='خدمات انجام\u200cشده')),
            ],
            options={
                'verbose_name': 'پروژه',
                'verbose_name_plural': 'پروژه\u200cها',
                'ordering': ['-project_date', '-created_at'],
            },
        ),
    ]
